[buildPlans.letter]
family = "Letter"
spacing = "term"
serifs = "sans"
no-cv-ss = true

[buildPlans.letter.variants.design]
f = "flat-hook"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless"
t = "flat-hook"
y = "straight-turn"
lower-lambda = "straight-turn"
lower-mu = "tailless"
lower-xi = "rounded"
cyrl-capital-ka = "symmetric-touching-bottom-right-serifed"
one = "base"
underscore = "above-baseline"
number-sign = "slanted"
percent = "rings-continuous-slash"
bar = "force-upright"

  [buildPlans.letter.ligations]
    inherits = "dlig"
